/*
 * Statbotics REST API
 *
 * The REST API for Statbotics. Please be nice to our servers! If you are looking to do large-scale data science projects, use the CSV exports on the GitHub repo.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace Statbotics.Api;

using System;
using System.Net.Http;
  using System.Collections.ObjectModel;

using Statbotics.Client;

using Statbotics.Model;
  /// <summary>
  /// Represents a collection of functions to interact with the API endpoints
  /// </summary>
  internal interface IV2TeamApiSync : IApiAccessor
  {
    #region Synchronous Operations
      /// <summary>
      /// Read Team
      /// </summary>
        /// <remarks>
        /// Get a single Team object containing team name, location, normalized EPA statistics, and winrate.
        /// </remarks>
      /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
      /// <param name="team"></param>
      /// <returns>Object</returns>
      Object ReadTeamV2TeamTeamGet(int team);
      
      /// <summary>
      /// Read Team
      /// </summary>
      /// <remarks>
      /// Get a single Team object containing team name, location, normalized EPA statistics, and winrate.
      /// </remarks>
      /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
      /// <param name="team"></param>
      /// <returns>ApiResponse of Object</returns>
      ApiResponse<Object> ReadTeamV2TeamTeamGetWithHttpInfo(int team);
      /// <summary>
      /// Read Teams District
      /// </summary>
        /// <remarks>
        /// Get a list of Team objects from a single district. Specify lowercase district abbreviation, ex: fnc, fim
        /// </remarks>
      /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
      /// <param name="district"></param>
      /// <returns>Collection&lt;Object&gt;</returns>
      Collection<Object> ReadTeamsDistrictV2TeamsDistrictDistrictGet(string district);
      
      /// <summary>
      /// Read Teams District
      /// </summary>
      /// <remarks>
      /// Get a list of Team objects from a single district. Specify lowercase district abbreviation, ex: fnc, fim
      /// </remarks>
      /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
      /// <param name="district"></param>
      /// <returns>ApiResponse of Collection&lt;Object&gt;</returns>
      ApiResponse<Collection<Object>> ReadTeamsDistrictV2TeamsDistrictDistrictGetWithHttpInfo(string district);
      /// <summary>
      /// Read Teams State
      /// </summary>
        /// <remarks>
        /// Get a list of Team objects from a single state. Specify uppercase state abbreviation, ex: NC, CA
        /// </remarks>
      /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
      /// <param name="state"></param>
      /// <returns>Collection&lt;Object&gt;</returns>
      Collection<Object> ReadTeamsStateV2TeamsStateStateGet(string state);
      
      /// <summary>
      /// Read Teams State
      /// </summary>
      /// <remarks>
      /// Get a list of Team objects from a single state. Specify uppercase state abbreviation, ex: NC, CA
      /// </remarks>
      /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
      /// <param name="state"></param>
      /// <returns>ApiResponse of Collection&lt;Object&gt;</returns>
      ApiResponse<Collection<Object>> ReadTeamsStateV2TeamsStateStateGetWithHttpInfo(string state);
      /// <summary>
      /// Read Teams
      /// </summary>
        /// <remarks>
        /// Get a list of Team objects with optional filters.
        /// </remarks>
      /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
      /// <param name="active"> (optional)</param>
      /// <param name="ascending"> (optional, default to true)</param>
      /// <param name="country"> (optional)</param>
      /// <param name="district"> (optional)</param>
      /// <param name="limit"> (optional, default to 100)</param>
      /// <param name="metric"> (optional, default to &quot;team&quot;)</param>
      /// <param name="offseason"> (optional)</param>
      /// <param name="offset"> (optional, default to 0)</param>
      /// <param name="state"> (optional)</param>
      /// <returns>Collection&lt;Object&gt;</returns>
      Collection<Object> ReadTeamsV2TeamsGet(bool? active = default, bool? ascending = default, string? country = default, string? district = default, int? limit = default, string? metric = default, bool? offseason = default, int? offset = default, string? state = default);
      
      /// <summary>
      /// Read Teams
      /// </summary>
      /// <remarks>
      /// Get a list of Team objects with optional filters.
      /// </remarks>
      /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
      /// <param name="active"> (optional)</param>
      /// <param name="ascending"> (optional, default to true)</param>
      /// <param name="country"> (optional)</param>
      /// <param name="district"> (optional)</param>
      /// <param name="limit"> (optional, default to 100)</param>
      /// <param name="metric"> (optional, default to &quot;team&quot;)</param>
      /// <param name="offseason"> (optional)</param>
      /// <param name="offset"> (optional, default to 0)</param>
      /// <param name="state"> (optional)</param>
      /// <returns>ApiResponse of Collection&lt;Object&gt;</returns>
      ApiResponse<Collection<Object>> ReadTeamsV2TeamsGetWithHttpInfo(bool? active = default, bool? ascending = default, string? country = default, string? district = default, int? limit = default, string? metric = default, bool? offseason = default, int? offset = default, string? state = default);
    #endregion Synchronous Operations
  }
  
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal interface IV2TeamApiAsync : IApiAccessor
    {
      #region Asynchronous Operations
        /// <summary>
        /// Read Team
        /// </summary>
        /// <remarks>
        /// Get a single Team object containing team name, location, normalized EPA statistics, and winrate.
        /// </remarks>
        /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
          /// <param name="team"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ReadTeamV2TeamTeamGetAsync(int team, CancellationToken cancellationToken = default);
          
          /// <summary>
          /// Read Team
          /// </summary>
          /// <remarks>
          /// Get a single Team object containing team name, location, normalized EPA statistics, and winrate.
          /// </remarks>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="team"></param>
          /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
          /// <returns>Task of ApiResponse (Object)</returns>
          System.Threading.Tasks.Task<ApiResponse<Object>> ReadTeamV2TeamTeamGetWithHttpInfoAsync(int team, CancellationToken cancellationToken = default);
        /// <summary>
        /// Read Teams District
        /// </summary>
        /// <remarks>
        /// Get a list of Team objects from a single district. Specify lowercase district abbreviation, ex: fnc, fim
        /// </remarks>
        /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
          /// <param name="district"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Collection&lt;Object&gt;</returns>
        System.Threading.Tasks.Task<Collection<Object>> ReadTeamsDistrictV2TeamsDistrictDistrictGetAsync(string district, CancellationToken cancellationToken = default);
          
          /// <summary>
          /// Read Teams District
          /// </summary>
          /// <remarks>
          /// Get a list of Team objects from a single district. Specify lowercase district abbreviation, ex: fnc, fim
          /// </remarks>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="district"></param>
          /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
          /// <returns>Task of ApiResponse (Collection&lt;Object&gt;)</returns>
          System.Threading.Tasks.Task<ApiResponse<Collection<Object>>> ReadTeamsDistrictV2TeamsDistrictDistrictGetWithHttpInfoAsync(string district, CancellationToken cancellationToken = default);
        /// <summary>
        /// Read Teams State
        /// </summary>
        /// <remarks>
        /// Get a list of Team objects from a single state. Specify uppercase state abbreviation, ex: NC, CA
        /// </remarks>
        /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
          /// <param name="state"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Collection&lt;Object&gt;</returns>
        System.Threading.Tasks.Task<Collection<Object>> ReadTeamsStateV2TeamsStateStateGetAsync(string state, CancellationToken cancellationToken = default);
          
          /// <summary>
          /// Read Teams State
          /// </summary>
          /// <remarks>
          /// Get a list of Team objects from a single state. Specify uppercase state abbreviation, ex: NC, CA
          /// </remarks>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="state"></param>
          /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
          /// <returns>Task of ApiResponse (Collection&lt;Object&gt;)</returns>
          System.Threading.Tasks.Task<ApiResponse<Collection<Object>>> ReadTeamsStateV2TeamsStateStateGetWithHttpInfoAsync(string state, CancellationToken cancellationToken = default);
        /// <summary>
        /// Read Teams
        /// </summary>
        /// <remarks>
        /// Get a list of Team objects with optional filters.
        /// </remarks>
        /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
          /// <param name="active"> (optional)</param>
          /// <param name="ascending"> (optional, default to true)</param>
          /// <param name="country"> (optional)</param>
          /// <param name="district"> (optional)</param>
          /// <param name="limit"> (optional, default to 100)</param>
          /// <param name="metric"> (optional, default to &quot;team&quot;)</param>
          /// <param name="offseason"> (optional)</param>
          /// <param name="offset"> (optional, default to 0)</param>
          /// <param name="state"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Collection&lt;Object&gt;</returns>
        System.Threading.Tasks.Task<Collection<Object>> ReadTeamsV2TeamsGetAsync(bool? active = default, bool? ascending = default, string? country = default, string? district = default, int? limit = default, string? metric = default, bool? offseason = default, int? offset = default, string? state = default, CancellationToken cancellationToken = default);
          
          /// <summary>
          /// Read Teams
          /// </summary>
          /// <remarks>
          /// Get a list of Team objects with optional filters.
          /// </remarks>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="active"> (optional)</param>
            /// <param name="ascending"> (optional, default to true)</param>
            /// <param name="country"> (optional)</param>
            /// <param name="district"> (optional)</param>
            /// <param name="limit"> (optional, default to 100)</param>
            /// <param name="metric"> (optional, default to &quot;team&quot;)</param>
            /// <param name="offseason"> (optional)</param>
            /// <param name="offset"> (optional, default to 0)</param>
            /// <param name="state"> (optional)</param>
          /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
          /// <returns>Task of ApiResponse (Collection&lt;Object&gt;)</returns>
          System.Threading.Tasks.Task<ApiResponse<Collection<Object>>> ReadTeamsV2TeamsGetWithHttpInfoAsync(bool? active = default, bool? ascending = default, string? country = default, string? district = default, int? limit = default, string? metric = default, bool? offseason = default, int? offset = default, string? state = default, CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
      }
    
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal interface IV2TeamApi : IV2TeamApiSync, IV2TeamApiAsync { }
    
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal partial class V2TeamApi : IV2TeamApi
    {
      private ExceptionFactory? _exceptionFactory = (name, response) => null;
      
      /// <summary>
      /// Initializes a new instance of the <see cref="V2TeamApi"/> class.
      /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
      /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
      /// </summary>
      /// <returns></returns>
      public V2TeamApi() : this((string)null) { }
      
      /// <summary>
      /// Initializes a new instance of the <see cref="V2TeamApi"/> class.
      /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
      /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
      /// </summary>
      /// <param name="basePath">The target service's base path in URL format.</param>
      /// <exception cref="ArgumentException"></exception>
      /// <returns></returns>
      public V2TeamApi(string basePath)
      {
        this.Configuration = Statbotics.Client.Configuration.MergeConfigurations(
        GlobalConfiguration.Instance,
        new Configuration { BasePath = basePath }
        );
        this.ApiClient = new ApiClient(this.Configuration.BasePath);
        this.Client =  this.ApiClient;
          this.AsynchronousClient = this.ApiClient;
        this.ExceptionFactory = Statbotics.Client.Configuration.DefaultExceptionFactory;
      }
      
      /// <summary>
      /// Initializes a new instance of the <see cref="V2TeamApi"/> class using Configuration object.
      /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
      /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
      /// </summary>
      /// <param name="configuration">An instance of Configuration.</param>
      /// <exception cref="ArgumentNullException"></exception>
      /// <returns></returns>
      public V2TeamApi(Statbotics.Client.Configuration configuration)
      {
        ArgumentNullException.ThrowIfNull(configuration);
        
        this.Configuration = Statbotics.Client.Configuration.MergeConfigurations(
        GlobalConfiguration.Instance,
        configuration
        );
        this.ApiClient = new ApiClient(this.Configuration.BasePath);
        this.Client = this.ApiClient;
          this.AsynchronousClient = this.ApiClient;
        ExceptionFactory = Statbotics.Client.Configuration.DefaultExceptionFactory;
      }
      
      /// <summary>
      /// Initializes a new instance of the <see cref="V2TeamApi"/> class.
      /// </summary>
      /// <param name="client">An instance of HttpClient.</param>
      /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
      /// <exception cref="ArgumentNullException"></exception>
      /// <returns></returns>
      /// <remarks>
      /// Some configuration settings will not be applied without passing an HttpClientHandler.
      /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
      /// </remarks>
      public V2TeamApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler) { }
      
      /// <summary>
      /// Initializes a new instance of the <see cref="V2TeamApi"/> class.
      /// </summary>
      /// <param name="client">An instance of HttpClient.</param>
      /// <param name="basePath">The target service's base path in URL format.</param>
      /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
      /// <exception cref="ArgumentNullException"></exception>
      /// <exception cref="ArgumentException"></exception>
      /// <returns></returns>
      /// <remarks>
      /// Some configuration settings will not be applied without passing an HttpClientHandler.
      /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
      /// </remarks>
      public V2TeamApi(HttpClient client, string basePath, HttpClientHandler handler = null)
      {
        ArgumentNullException.ThrowIfNull(client);
        
        this.Configuration = Statbotics.Client.Configuration.MergeConfigurations(
        GlobalConfiguration.Instance,
        new Configuration { BasePath = basePath }
        );
        this.ApiClient = new ApiClient(client, this.Configuration.BasePath, handler);
        this.Client =  this.ApiClient;
          this.AsynchronousClient = this.ApiClient;
        this.ExceptionFactory = Statbotics.Client.Configuration.DefaultExceptionFactory;
      }
      
      /// <summary>
      /// Initializes a new instance of the <see cref="V2TeamApi"/> class using Configuration object.
      /// </summary>
      /// <param name="client">An instance of HttpClient.</param>
      /// <param name="configuration">An instance of Configuration.</param>
      /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
      /// <exception cref="ArgumentNullException"></exception>
      /// <returns></returns>
      /// <remarks>
      /// Some configuration settings will not be applied without passing an HttpClientHandler.
      /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
      /// </remarks>
      public V2TeamApi(HttpClient client, Configuration configuration, HttpClientHandler handler = null)
      {
        ArgumentNullException.ThrowIfNull(configuration);
        ArgumentNullException.ThrowIfNull(client);
        
        this.Configuration = Statbotics.Client.Configuration.MergeConfigurations(
        GlobalConfiguration.Instance,
        configuration
        );
        this.ApiClient = new ApiClient(client, this.Configuration.BasePath, handler);
        this.Client = this.ApiClient;
          this.AsynchronousClient = this.ApiClient;
        ExceptionFactory = Statbotics.Client.Configuration.DefaultExceptionFactory;
      }
      
      /// <summary>
      /// Initializes a new instance of the <see cref="V2TeamApi"/> class
      /// using a Configuration object and client instance.
      /// </summary>
      /// <param name="client">The client interface for synchronous API access.</param>
      /// <param name="asyncClient">The client interface for asynchronous API access.</param>
      /// <param name="configuration">The configuration object.</param>
      /// <exception cref="ArgumentNullException"></exception>
      public V2TeamApi(Statbotics.Client.ISynchronousClient client, Statbotics.Client.IAsynchronousClient asyncClient, Statbotics.Client.IReadableConfiguration configuration)
      {
        ArgumentNullException.ThrowIfNull(client);
        
          ArgumentNullException.ThrowIfNull(asyncClient);
          
        ArgumentNullException.ThrowIfNull(configuration);
        
        this.Client = client;
          this.AsynchronousClient = asyncClient;
        this.Configuration = configuration;
        this.ExceptionFactory = Statbotics.Client.Configuration.DefaultExceptionFactory;
      }
      
      /// <summary>
      /// Holds the ApiClient if created
      /// </summary>
      public ApiClient ApiClient { get; set; } = null;
      
        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public IAsynchronousClient AsynchronousClient { get; set; }
      
      /// <summary>
      /// The client for accessing this underlying API synchronously.
      /// </summary>
      public ISynchronousClient Client { get; set; }
      
      /// <summary>
      /// Gets the base path of the API client.
      /// </summary>
      /// <value>The base path</value>
      public string GetBasePath() => this.Configuration.BasePath;
      
      /// <summary>
      /// Gets or sets the configuration object
      /// </summary>
      /// <value>An instance of the Configuration</value>
      public IReadableConfiguration Configuration { get; set; }
      
      /// <summary>
      /// Provides a factory method hook for the creation of exceptions.
      /// </summary>
      public ExceptionFactory ExceptionFactory
      {
        get
        {
          if (_exceptionFactory is not null && _exceptionFactory.GetInvocationList().Length > 1)
          {
            throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
          }
          
          return _exceptionFactory;
        }
        set { _exceptionFactory = value; }
      }
      
        /// <summary>
        /// Read Team Get a single Team object containing team name, location, normalized EPA statistics, and winrate.
        /// </summary>
        /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="team"></param>
        /// <returns>Object</returns>
        public Object ReadTeamV2TeamTeamGet(int team)
        {
          Statbotics.Client.ApiResponse<Object> localVarResponse = ReadTeamV2TeamTeamGetWithHttpInfo(team);
            return localVarResponse.Data;
          }
          
          /// <summary>
          /// Read Team Get a single Team object containing team name, location, normalized EPA statistics, and winrate.
          /// </summary>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
          /// <param name="team"></param>
          /// <returns>ApiResponse of Object</returns>
          public ApiResponse<Object> ReadTeamV2TeamTeamGetWithHttpInfo(int team)
          {
            RequestOptions localVarRequestOptions = new RequestOptions();
            
            string[] _contentTypes = [
            ];
            
            // to determine the Accept header
            string[] _accepts = [
                "application/json"
            ];
            
            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType is not null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            
            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept is not null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            
                localVarRequestOptions.PathParameters.Add("team", ClientUtils.ParameterToString(team)); // path parameter
            
            
            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v2/team/{team}", localVarRequestOptions, this.Configuration);
            
            if (this.ExceptionFactory is not null)
            {
              Exception _exception = this.ExceptionFactory("ReadTeamV2TeamTeamGet", localVarResponse);
              if (_exception is not null)
              {
                throw _exception;
              }
            }
            
            return localVarResponse;
          }
          
          /// <summary>
          /// Read Team Get a single Team object containing team name, location, normalized EPA statistics, and winrate.
          /// </summary>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="team"></param>
          /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
          /// <returns>Task of Object</returns>
          public async System.Threading.Tasks.Task<Object> ReadTeamV2TeamTeamGetAsync(int team, CancellationToken cancellationToken = default)
            {
              Statbotics.Client.ApiResponse<Object> localVarResponse = await ReadTeamV2TeamTeamGetWithHttpInfoAsync(team, cancellationToken).ConfigureAwait(false);
                return localVarResponse.Data;
              }
              
              /// <summary>
              /// Read Team Get a single Team object containing team name, location, normalized EPA statistics, and winrate.
              /// </summary>
              /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
                /// <param name="team"></param>
              /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
              /// <returns>Task of ApiResponse (Object)</returns>
              public async System.Threading.Tasks.Task<Statbotics.Client.ApiResponse<Object>> ReadTeamV2TeamTeamGetWithHttpInfoAsync(int team, CancellationToken cancellationToken = default)
              {
                RequestOptions localVarRequestOptions = new RequestOptions();
                
                string[] _contentTypes = [
                ];
                
                // to determine the Accept header
                string[] _accepts = [
                    "application/json"
                ];
                
                var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
                if (localVarContentType is not null)
                {
                  localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
                }
                
                var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept is not null)
                {
                  localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
                
                    localVarRequestOptions.PathParameters.Add("team", ClientUtils.ParameterToString(team)); // path parameter
                
                // make the HTTP request
                var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v2/team/{team}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);
                
                if (this.ExceptionFactory is not null)
                {
                  Exception _exception = this.ExceptionFactory("ReadTeamV2TeamTeamGet", localVarResponse);
                  if (_exception is not null)
                  {
                    throw _exception;
                  }
                }
                
                return localVarResponse;
              }        /// <summary>
        /// Read Teams District Get a list of Team objects from a single district. Specify lowercase district abbreviation, ex: fnc, fim
        /// </summary>
        /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="district"></param>
        /// <returns>Collection&lt;Object&gt;</returns>
        public Collection<Object> ReadTeamsDistrictV2TeamsDistrictDistrictGet(string district)
        {
          Statbotics.Client.ApiResponse<Collection<Object>> localVarResponse = ReadTeamsDistrictV2TeamsDistrictDistrictGetWithHttpInfo(district);
            return localVarResponse.Data;
          }
          
          /// <summary>
          /// Read Teams District Get a list of Team objects from a single district. Specify lowercase district abbreviation, ex: fnc, fim
          /// </summary>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
          /// <param name="district"></param>
          /// <returns>ApiResponse of Collection&lt;Object&gt;</returns>
          public ApiResponse<Collection<Object>> ReadTeamsDistrictV2TeamsDistrictDistrictGetWithHttpInfo(string district)
          {
                  // verify the required parameter 'district' is set
                  if (district is null)
                  {
                    throw new ApiException(400, "Missing required parameter 'district' when calling V2TeamApi->ReadTeamsDistrictV2TeamsDistrictDistrictGet");
                  }
                  
            RequestOptions localVarRequestOptions = new RequestOptions();
            
            string[] _contentTypes = [
            ];
            
            // to determine the Accept header
            string[] _accepts = [
                "application/json"
            ];
            
            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType is not null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            
            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept is not null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            
                localVarRequestOptions.PathParameters.Add("district", ClientUtils.ParameterToString(district)); // path parameter
            
            
            // make the HTTP request
            var localVarResponse = this.Client.Get<Collection<Object>>("/v2/teams/district/{district}", localVarRequestOptions, this.Configuration);
            
            if (this.ExceptionFactory is not null)
            {
              Exception _exception = this.ExceptionFactory("ReadTeamsDistrictV2TeamsDistrictDistrictGet", localVarResponse);
              if (_exception is not null)
              {
                throw _exception;
              }
            }
            
            return localVarResponse;
          }
          
          /// <summary>
          /// Read Teams District Get a list of Team objects from a single district. Specify lowercase district abbreviation, ex: fnc, fim
          /// </summary>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="district"></param>
          /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
          /// <returns>Task of Collection&lt;Object&gt;</returns>
          public async System.Threading.Tasks.Task<Collection<Object>> ReadTeamsDistrictV2TeamsDistrictDistrictGetAsync(string district, CancellationToken cancellationToken = default)
            {
              Statbotics.Client.ApiResponse<Collection<Object>> localVarResponse = await ReadTeamsDistrictV2TeamsDistrictDistrictGetWithHttpInfoAsync(district, cancellationToken).ConfigureAwait(false);
                return localVarResponse.Data;
              }
              
              /// <summary>
              /// Read Teams District Get a list of Team objects from a single district. Specify lowercase district abbreviation, ex: fnc, fim
              /// </summary>
              /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
                /// <param name="district"></param>
              /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
              /// <returns>Task of ApiResponse (Collection&lt;Object&gt;)</returns>
              public async System.Threading.Tasks.Task<Statbotics.Client.ApiResponse<Collection<Object>>> ReadTeamsDistrictV2TeamsDistrictDistrictGetWithHttpInfoAsync(string district, CancellationToken cancellationToken = default)
              {
                      // verify the required parameter 'district' is set
                      if (district is null)
                      {
                        throw new ApiException(400, "Missing required parameter 'district' when calling V2TeamApi->ReadTeamsDistrictV2TeamsDistrictDistrictGet");
                      }
                      
                RequestOptions localVarRequestOptions = new RequestOptions();
                
                string[] _contentTypes = [
                ];
                
                // to determine the Accept header
                string[] _accepts = [
                    "application/json"
                ];
                
                var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
                if (localVarContentType is not null)
                {
                  localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
                }
                
                var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept is not null)
                {
                  localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
                
                    localVarRequestOptions.PathParameters.Add("district", ClientUtils.ParameterToString(district)); // path parameter
                
                // make the HTTP request
                var localVarResponse = await this.AsynchronousClient.GetAsync<Collection<Object>>("/v2/teams/district/{district}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);
                
                if (this.ExceptionFactory is not null)
                {
                  Exception _exception = this.ExceptionFactory("ReadTeamsDistrictV2TeamsDistrictDistrictGet", localVarResponse);
                  if (_exception is not null)
                  {
                    throw _exception;
                  }
                }
                
                return localVarResponse;
              }        /// <summary>
        /// Read Teams State Get a list of Team objects from a single state. Specify uppercase state abbreviation, ex: NC, CA
        /// </summary>
        /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="state"></param>
        /// <returns>Collection&lt;Object&gt;</returns>
        public Collection<Object> ReadTeamsStateV2TeamsStateStateGet(string state)
        {
          Statbotics.Client.ApiResponse<Collection<Object>> localVarResponse = ReadTeamsStateV2TeamsStateStateGetWithHttpInfo(state);
            return localVarResponse.Data;
          }
          
          /// <summary>
          /// Read Teams State Get a list of Team objects from a single state. Specify uppercase state abbreviation, ex: NC, CA
          /// </summary>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
          /// <param name="state"></param>
          /// <returns>ApiResponse of Collection&lt;Object&gt;</returns>
          public ApiResponse<Collection<Object>> ReadTeamsStateV2TeamsStateStateGetWithHttpInfo(string state)
          {
                  // verify the required parameter 'state' is set
                  if (state is null)
                  {
                    throw new ApiException(400, "Missing required parameter 'state' when calling V2TeamApi->ReadTeamsStateV2TeamsStateStateGet");
                  }
                  
            RequestOptions localVarRequestOptions = new RequestOptions();
            
            string[] _contentTypes = [
            ];
            
            // to determine the Accept header
            string[] _accepts = [
                "application/json"
            ];
            
            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType is not null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            
            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept is not null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            
                localVarRequestOptions.PathParameters.Add("state", ClientUtils.ParameterToString(state)); // path parameter
            
            
            // make the HTTP request
            var localVarResponse = this.Client.Get<Collection<Object>>("/v2/teams/state/{state}", localVarRequestOptions, this.Configuration);
            
            if (this.ExceptionFactory is not null)
            {
              Exception _exception = this.ExceptionFactory("ReadTeamsStateV2TeamsStateStateGet", localVarResponse);
              if (_exception is not null)
              {
                throw _exception;
              }
            }
            
            return localVarResponse;
          }
          
          /// <summary>
          /// Read Teams State Get a list of Team objects from a single state. Specify uppercase state abbreviation, ex: NC, CA
          /// </summary>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="state"></param>
          /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
          /// <returns>Task of Collection&lt;Object&gt;</returns>
          public async System.Threading.Tasks.Task<Collection<Object>> ReadTeamsStateV2TeamsStateStateGetAsync(string state, CancellationToken cancellationToken = default)
            {
              Statbotics.Client.ApiResponse<Collection<Object>> localVarResponse = await ReadTeamsStateV2TeamsStateStateGetWithHttpInfoAsync(state, cancellationToken).ConfigureAwait(false);
                return localVarResponse.Data;
              }
              
              /// <summary>
              /// Read Teams State Get a list of Team objects from a single state. Specify uppercase state abbreviation, ex: NC, CA
              /// </summary>
              /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
                /// <param name="state"></param>
              /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
              /// <returns>Task of ApiResponse (Collection&lt;Object&gt;)</returns>
              public async System.Threading.Tasks.Task<Statbotics.Client.ApiResponse<Collection<Object>>> ReadTeamsStateV2TeamsStateStateGetWithHttpInfoAsync(string state, CancellationToken cancellationToken = default)
              {
                      // verify the required parameter 'state' is set
                      if (state is null)
                      {
                        throw new ApiException(400, "Missing required parameter 'state' when calling V2TeamApi->ReadTeamsStateV2TeamsStateStateGet");
                      }
                      
                RequestOptions localVarRequestOptions = new RequestOptions();
                
                string[] _contentTypes = [
                ];
                
                // to determine the Accept header
                string[] _accepts = [
                    "application/json"
                ];
                
                var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
                if (localVarContentType is not null)
                {
                  localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
                }
                
                var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept is not null)
                {
                  localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
                
                    localVarRequestOptions.PathParameters.Add("state", ClientUtils.ParameterToString(state)); // path parameter
                
                // make the HTTP request
                var localVarResponse = await this.AsynchronousClient.GetAsync<Collection<Object>>("/v2/teams/state/{state}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);
                
                if (this.ExceptionFactory is not null)
                {
                  Exception _exception = this.ExceptionFactory("ReadTeamsStateV2TeamsStateStateGet", localVarResponse);
                  if (_exception is not null)
                  {
                    throw _exception;
                  }
                }
                
                return localVarResponse;
              }        /// <summary>
        /// Read Teams Get a list of Team objects with optional filters.
        /// </summary>
        /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="active"> (optional)</param>
        /// <param name="ascending"> (optional, default to true)</param>
        /// <param name="country"> (optional)</param>
        /// <param name="district"> (optional)</param>
        /// <param name="limit"> (optional, default to 100)</param>
        /// <param name="metric"> (optional, default to &quot;team&quot;)</param>
        /// <param name="offseason"> (optional)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="state"> (optional)</param>
        /// <returns>Collection&lt;Object&gt;</returns>
        public Collection<Object> ReadTeamsV2TeamsGet(bool? active = default, bool? ascending = default, string? country = default, string? district = default, int? limit = default, string? metric = default, bool? offseason = default, int? offset = default, string? state = default)
        {
          Statbotics.Client.ApiResponse<Collection<Object>> localVarResponse = ReadTeamsV2TeamsGetWithHttpInfo(active, ascending, country, district, limit, metric, offseason, offset, state);
            return localVarResponse.Data;
          }
          
          /// <summary>
          /// Read Teams Get a list of Team objects with optional filters.
          /// </summary>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
          /// <param name="active"> (optional)</param>
          /// <param name="ascending"> (optional, default to true)</param>
          /// <param name="country"> (optional)</param>
          /// <param name="district"> (optional)</param>
          /// <param name="limit"> (optional, default to 100)</param>
          /// <param name="metric"> (optional, default to &quot;team&quot;)</param>
          /// <param name="offseason"> (optional)</param>
          /// <param name="offset"> (optional, default to 0)</param>
          /// <param name="state"> (optional)</param>
          /// <returns>ApiResponse of Collection&lt;Object&gt;</returns>
          public ApiResponse<Collection<Object>> ReadTeamsV2TeamsGetWithHttpInfo(bool? active = default, bool? ascending = default, string? country = default, string? district = default, int? limit = default, string? metric = default, bool? offseason = default, int? offset = default, string? state = default)
          {
            RequestOptions localVarRequestOptions = new RequestOptions();
            
            string[] _contentTypes = [
            ];
            
            // to determine the Accept header
            string[] _accepts = [
                "application/json"
            ];
            
            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType is not null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            
            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept is not null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            
                if (active is not null)
                {
                    localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "active", active));
                }
                
                if (ascending is not null)
                {
                    localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "ascending", ascending));
                }
                
                if (country is not null)
                {
                    localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "country", country));
                }
                
                if (district is not null)
                {
                    localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "district", district));
                }
                
                if (limit is not null)
                {
                    localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
                }
                
                if (metric is not null)
                {
                    localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "metric", metric));
                }
                
                if (offseason is not null)
                {
                    localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "offseason", offseason));
                }
                
                if (offset is not null)
                {
                    localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
                }
                
                if (state is not null)
                {
                    localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "state", state));
                }
                
            
            
            // make the HTTP request
            var localVarResponse = this.Client.Get<Collection<Object>>("/v2/teams", localVarRequestOptions, this.Configuration);
            
            if (this.ExceptionFactory is not null)
            {
              Exception _exception = this.ExceptionFactory("ReadTeamsV2TeamsGet", localVarResponse);
              if (_exception is not null)
              {
                throw _exception;
              }
            }
            
            return localVarResponse;
          }
          
          /// <summary>
          /// Read Teams Get a list of Team objects with optional filters.
          /// </summary>
          /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
            /// <param name="active"> (optional)</param>
            /// <param name="ascending"> (optional, default to true)</param>
            /// <param name="country"> (optional)</param>
            /// <param name="district"> (optional)</param>
            /// <param name="limit"> (optional, default to 100)</param>
            /// <param name="metric"> (optional, default to &quot;team&quot;)</param>
            /// <param name="offseason"> (optional)</param>
            /// <param name="offset"> (optional, default to 0)</param>
            /// <param name="state"> (optional)</param>
          /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
          /// <returns>Task of Collection&lt;Object&gt;</returns>
          public async System.Threading.Tasks.Task<Collection<Object>> ReadTeamsV2TeamsGetAsync(bool? active = default, bool? ascending = default, string? country = default, string? district = default, int? limit = default, string? metric = default, bool? offseason = default, int? offset = default, string? state = default, CancellationToken cancellationToken = default)
            {
              Statbotics.Client.ApiResponse<Collection<Object>> localVarResponse = await ReadTeamsV2TeamsGetWithHttpInfoAsync(active, ascending, country, district, limit, metric, offseason, offset, state, cancellationToken).ConfigureAwait(false);
                return localVarResponse.Data;
              }
              
              /// <summary>
              /// Read Teams Get a list of Team objects with optional filters.
              /// </summary>
              /// <exception cref="Statbotics.Client.ApiException">Thrown when fails to make API call</exception>
                /// <param name="active"> (optional)</param>
                /// <param name="ascending"> (optional, default to true)</param>
                /// <param name="country"> (optional)</param>
                /// <param name="district"> (optional)</param>
                /// <param name="limit"> (optional, default to 100)</param>
                /// <param name="metric"> (optional, default to &quot;team&quot;)</param>
                /// <param name="offseason"> (optional)</param>
                /// <param name="offset"> (optional, default to 0)</param>
                /// <param name="state"> (optional)</param>
              /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
              /// <returns>Task of ApiResponse (Collection&lt;Object&gt;)</returns>
              public async System.Threading.Tasks.Task<Statbotics.Client.ApiResponse<Collection<Object>>> ReadTeamsV2TeamsGetWithHttpInfoAsync(bool? active = default, bool? ascending = default, string? country = default, string? district = default, int? limit = default, string? metric = default, bool? offseason = default, int? offset = default, string? state = default, CancellationToken cancellationToken = default)
              {
                RequestOptions localVarRequestOptions = new RequestOptions();
                
                string[] _contentTypes = [
                ];
                
                // to determine the Accept header
                string[] _accepts = [
                    "application/json"
                ];
                
                var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
                if (localVarContentType is not null)
                {
                  localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
                }
                
                var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
                if (localVarAccept is not null)
                {
                  localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
                }
                
                    if (active is not null)
                    {
                      localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "active", active));
                    }
                    
                    if (ascending is not null)
                    {
                      localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "ascending", ascending));
                    }
                    
                    if (country is not null)
                    {
                      localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "country", country));
                    }
                    
                    if (district is not null)
                    {
                      localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "district", district));
                    }
                    
                    if (limit is not null)
                    {
                      localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
                    }
                    
                    if (metric is not null)
                    {
                      localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "metric", metric));
                    }
                    
                    if (offseason is not null)
                    {
                      localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "offseason", offseason));
                    }
                    
                    if (offset is not null)
                    {
                      localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
                    }
                    
                    if (state is not null)
                    {
                      localVarRequestOptions.QueryParameters.Add(Statbotics.Client.ClientUtils.ParameterToMultiMap("", "state", state));
                    }
                    
                
                // make the HTTP request
                var localVarResponse = await this.AsynchronousClient.GetAsync<Collection<Object>>("/v2/teams", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);
                
                if (this.ExceptionFactory is not null)
                {
                  Exception _exception = this.ExceptionFactory("ReadTeamsV2TeamsGet", localVarResponse);
                  if (_exception is not null)
                  {
                    throw _exception;
                  }
                }
                
                return localVarResponse;
              }
            }
