#!/usr/bin/env bash
set -euo pipefail

SPEC_URL="https://www.thebluealliance.com/swagger/api_v3.json"
OUTPUT_DIR="src"
GENERATOR_IMAGE="openapitools/openapi-generator-cli"
LIBRARY="httpclient"
#ADDITIONAL_PROPERTIES="packageName=Org.OpenAPITools,packageVersion=1.0.0,nullableReferenceTypes=true"
CLEAN_OUTPUT="false"

usage() {
  cat <<'EOF'
Usage: scripts/generate-csharp-sdk.sh [options]

Options:
  --spec-url URL                  OpenAPI spec URL
  --output-dir DIR                Output directory relative to repo root
  --generator-image IMAGE         OpenAPI Generator Docker image
  --library NAME                  C# generator library (default: httpclient)
  --additional-properties PROPS   Comma-separated generator additional properties
  --clean-output                  Remove output directory before generation
  -h, --help                      Show this help message
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --spec-url)
      SPEC_URL="$2"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --generator-image)
      GENERATOR_IMAGE="$2"
      shift 2
      ;;
    --library)
      LIBRARY="$2"
      shift 2
      ;;
    --additional-properties)
      ADDITIONAL_PROPERTIES="$2"
      shift 2
      ;;
    --clean-output)
      CLEAN_OUTPUT="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

for cmd in curl jq docker; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Required command not found: $cmd" >&2
    exit 1
  fi
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUTPUT_PATH="${REPO_ROOT}/${OUTPUT_DIR}"
TEMP_SPEC_PATH="${REPO_ROOT}/.tmp.tba-fixed.json"
RAW_SPEC_PATH="${REPO_ROOT}/.tmp.tba-raw.json"

cleanup() {
  rm -f "$TEMP_SPEC_PATH" "$RAW_SPEC_PATH"
}
trap cleanup EXIT

purge_stale_generated_model_files() {
  local model_dir="${REPO_ROOT}/services/TheBlueAlliance/src/TheBlueAlliance/Model"
  local removed=0

  if [[ ! -d "$model_dir" ]]; then
    return
  fi

  # Remove only model files previously generated by OpenAPI Generator.
  # This avoids deleting hand-authored partials/additions that do not carry the generated header.
  while IFS= read -r -d '' file; do
    if head -n 20 "$file" | grep -q "Generated by: https://github.com/openapitools/openapi-generator.git"; then
      rm -f "$file"
      removed=$((removed + 1))
    fi
  done < <(find "$model_dir" -maxdepth 1 -type f -name "*.cs" -print0)

  echo "Removed $removed previously generated model file(s) from: $model_dir"
}

echo "Preparing compatibility-normalized OpenAPI spec..."
curl -fsSL "$SPEC_URL" -o "$RAW_SPEC_PATH"

if ! jq -e '.components.schemas.Team_Event_Status_playoff' "$RAW_SPEC_PATH" >/dev/null; then
  echo "Schema components.schemas.Team_Event_Status_playoff was not found in source spec." >&2
  exit 1
fi

jq '
  if (.components.schemas.Team_Event_Status_playoff.type | type) == "array" then
    .components.schemas.Team_Event_Status_playoff.type = "object"
    | .components.schemas.Team_Event_Status_playoff.nullable = true
  else
    .
  end
' "$RAW_SPEC_PATH" > "$TEMP_SPEC_PATH"

if [[ "$CLEAN_OUTPUT" == "true" && -d "$OUTPUT_PATH" ]]; then
  echo "Removing existing output directory: $OUTPUT_PATH"
  rm -rf "$OUTPUT_PATH"
fi

# Keep output deterministic by removing stale generated model files before regeneration.
purge_stale_generated_model_files

echo "Running OpenAPI Generator in Docker..."
docker run --rm \
  -v "${REPO_ROOT}/services/TheBlueAlliance:/local" \
  -v "${REPO_ROOT}:/repo_root" \
  -v "/mnt/d/gh/me/openapi-generator-csharp-system-text-json:/api_template" \
  "$GENERATOR_IMAGE" generate \
  -i "/repo_root/.tmp.tba-fixed.json" \
  -g csharp \
  -o "/local" \
  -t /api_template \
  -c "/local/openapitools.json" \
  --library "$LIBRARY" #\
#  --additional-properties "$ADDITIONAL_PROPERTIES"

echo "Generation complete: $OUTPUT_PATH"
