/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TheBlueAlliance.Model;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

/// <summary>
/// Defines AutoLineRobot_2024
/// </summary>
[Microsoft.Extensions.EnumStrings.EnumStrings(ExtensionNamespace = "TheBlueAlliance.Model.AutoLineRobot2024Extensions", ExtensionClassModifiers = "public static")]
[JsonConverter(typeof(JsonStringEnumConverterWithEnumMemberSupport<AutoLineRobot2024>))]
public enum AutoLineRobot2024
{
    /// <summary>
    /// Enum No for value: No
    /// </summary>
    [EnumMember(Value = "No")]
    No = 1,

    /// <summary>
    /// Enum Yes for value: Yes
    /// </summary>
    [EnumMember(Value = "Yes")]
    Yes = 2
}

/// <summary>
/// Converts <see cref="AutoLineRobot2024"/> to and from the JSON value
/// </summary>
public static class AutoLineRobot2024ValueConverter
{
    /// <summary>
    /// Parses a given value to <see cref="AutoLineRobot2024"/>
    /// </summary>
    /// <param name="value"></param>
    /// <returns></returns>
    public static AutoLineRobot2024? FromStringOrDefault(string value)
    {
        return value switch
        {
            "No" => AutoLineRobot2024.No,
            "Yes" => AutoLineRobot2024.Yes,
            _ => null
        };
    }
}

