/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

    namespace TheBlueAlliance.Model;
    
    using System.Runtime.Serialization;
    using System.Text;
    using System.Text.Json;
    using System.Text.Json.Serialization;
  using System.Collections.ObjectModel;
    
    /// <summary>
/// Defines AutoChargeStationRobot_2023
/// </summary>
[Microsoft.Extensions.EnumStrings.EnumStrings(ExtensionNamespace = "TheBlueAlliance.Model.AutoChargeStationRobot2023Extensions", ExtensionClassModifiers ="public static")]
[JsonConverter(typeof(JsonStringEnumConverterWithEnumMemberSupport<AutoChargeStationRobot2023>))]
public enum AutoChargeStationRobot2023
{
      /// <summary>
      /// Enum Docked for value: Docked
      /// </summary>
      [EnumMember(Value = "Docked")]
      Docked = 1,
        
      /// <summary>
      /// Enum None for value: None
      /// </summary>
      [EnumMember(Value = "None")]
      None = 2
}
  
  /// <summary>
  /// Converts <see cref="AutoChargeStationRobot2023"/> to and from the JSON value
  /// </summary>
  public static class AutoChargeStationRobot2023ValueConverter
  {    
    /// <summary>
    /// Parses a given value to <see cref="AutoChargeStationRobot2023"/>
    /// </summary>
    /// <param name="value"></param>
    /// <returns></returns>
    public static AutoChargeStationRobot2023? FromStringOrDefault(string value)
    {
      return value switch
      {
            "Docked" => AutoChargeStationRobot2023.Docked,            "None" => AutoChargeStationRobot2023.None,
          _ => null
        };
      }
    }
  
