/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

    namespace TheBlueAlliance.Model;
    
    using System.Runtime.Serialization;
    using System.Text;
    using System.Text.Json;
    using System.Text.Json.Serialization;
  using System.Collections.ObjectModel;
    
    /// <summary>
/// MediaDetailsOneOf1
/// </summary>
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
  public partial record MediaDetailsOneOf1
  {
              // yup
              /// <summary>
              /// Initializes a new instance of the <see cref="MediaDetailsOneOf1" /> class.
              /// </summary>
              [JsonConstructor]
              protected MediaDetailsOneOf1() { 
            }
            
        /// <summary>
        /// Initializes a new instance of the <see cref="MediaDetailsOneOf1" /> class.
        /// </summary>
            /// <param name="authorId">authorId (required).</param>
            /// <param name="authorName">authorName (required).</param>
            /// <param name="authorUrl">authorUrl (required).</param>
            /// <param name="height">height (required).</param>
            /// <param name="html">html (required).</param>
            /// <param name="mediaId">mediaId (required).</param>
            /// <param name="providerName">providerName (required).</param>
            /// <param name="providerUrl">providerUrl (required).</param>
            /// <param name="thumbnailHeight">thumbnailHeight (required).</param>
            /// <param name="thumbnailUrl">thumbnailUrl (required).</param>
            /// <param name="thumbnailWidth">thumbnailWidth (required).</param>
            /// <param name="title">title (required).</param>
            /// <param name="type">type (required).</param>
            /// <param name="width">width (required).</param>
            /// <param name="varVersion">varVersion (required).</param>
        public MediaDetailsOneOf1(int authorId, string authorName, string authorUrl, int? height, string html, string mediaId, string providerName, string providerUrl, int thumbnailHeight, string thumbnailUrl, int thumbnailWidth, string title, string type, int width, string varVersion)
        {
                      this.AuthorId = authorId;
                      // to ensure "authorName" is required (not null)
                      ArgumentNullException.ThrowIfNull(authorName);
                      this.AuthorName = authorName;
                        
                      // to ensure "authorUrl" is required (not null)
                      ArgumentNullException.ThrowIfNull(authorUrl);
                      this.AuthorUrl = authorUrl;
                        
                      // to ensure "height" is required (not null)
                      ArgumentNullException.ThrowIfNull(height);
                      this.Height = height;
                        
                      // to ensure "html" is required (not null)
                      ArgumentNullException.ThrowIfNull(html);
                      this.Html = html;
                        
                      // to ensure "mediaId" is required (not null)
                      ArgumentNullException.ThrowIfNull(mediaId);
                      this.MediaId = mediaId;
                        
                      // to ensure "providerName" is required (not null)
                      ArgumentNullException.ThrowIfNull(providerName);
                      this.ProviderName = providerName;
                        
                      // to ensure "providerUrl" is required (not null)
                      ArgumentNullException.ThrowIfNull(providerUrl);
                      this.ProviderUrl = providerUrl;
                        
                      this.ThumbnailHeight = thumbnailHeight;
                      // to ensure "thumbnailUrl" is required (not null)
                      ArgumentNullException.ThrowIfNull(thumbnailUrl);
                      this.ThumbnailUrl = thumbnailUrl;
                        
                      this.ThumbnailWidth = thumbnailWidth;
                      // to ensure "title" is required (not null)
                      ArgumentNullException.ThrowIfNull(title);
                      this.Title = title;
                        
                      // to ensure "type" is required (not null)
                      ArgumentNullException.ThrowIfNull(type);
                      this.Type = type;
                        
                      this.Width = width;
                      // to ensure "varVersion" is required (not null)
                      ArgumentNullException.ThrowIfNull(varVersion);
                      this.VarVersion = varVersion;
        }
        
              /// <summary>
              /// Gets or Sets AuthorId
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("author_id")]
                  public int AuthorId { get; set; }
                  
              /// <summary>
              /// Gets or Sets AuthorName
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("author_name")]
                  public string AuthorName { get; set; }
                  
              /// <summary>
              /// Gets or Sets AuthorUrl
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("author_url")]
                  public string AuthorUrl { get; set; }
                  
              /// <summary>
              /// Gets or Sets Height
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("height")]
                  public int? Height { get; set; }
                  
              /// <summary>
              /// Gets or Sets Html
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("html")]
                  public string Html { get; set; }
                  
              /// <summary>
              /// Gets or Sets MediaId
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("media_id")]
                  public string MediaId { get; set; }
                  
              /// <summary>
              /// Gets or Sets ProviderName
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("provider_name")]
                  public string ProviderName { get; set; }
                  
              /// <summary>
              /// Gets or Sets ProviderUrl
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("provider_url")]
                  public string ProviderUrl { get; set; }
                  
              /// <summary>
              /// Gets or Sets ThumbnailHeight
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("thumbnail_height")]
                  public int ThumbnailHeight { get; set; }
                  
              /// <summary>
              /// Gets or Sets ThumbnailUrl
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("thumbnail_url")]
                  public string ThumbnailUrl { get; set; }
                  
              /// <summary>
              /// Gets or Sets ThumbnailWidth
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("thumbnail_width")]
                  public int ThumbnailWidth { get; set; }
                  
              /// <summary>
              /// Gets or Sets Title
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("title")]
                  public string Title { get; set; }
                  
              /// <summary>
              /// Gets or Sets Type
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("type")]
                  public string Type { get; set; }
                  
              /// <summary>
              /// Gets or Sets Width
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("width")]
                  public int Width { get; set; }
                  
              /// <summary>
              /// Gets or Sets VarVersion
              /// </summary>
                [JsonRequired]
                  [JsonPropertyName("version")]
                  public string VarVersion { get; set; }
                  
              /// <summary>
              /// Returns the JSON string presentation of the object
              /// </summary>
              /// <returns>JSON string presentation of the object</returns>
              public string ToJson()
              {
                return JsonSerializer.Serialize(this);
              }
            }
            #pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
