// <auto-generated/>
#pragma warning disable CS0618
using Common.Statbotics.Api.V2.Matches.Team.Item.Event;
using Common.Statbotics.Api.V2.Matches.Team.Item.Year;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Common.Statbotics.Api.V2.Matches.Team.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\matches\team\{team}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTeamItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The event property</summary>
        public global::Common.Statbotics.Api.V2.Matches.Team.Item.Event.EventRequestBuilder Event
        {
            get => new global::Common.Statbotics.Api.V2.Matches.Team.Item.Event.EventRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The year property</summary>
        public global::Common.Statbotics.Api.V2.Matches.Team.Item.Year.YearRequestBuilder Year
        {
            get => new global::Common.Statbotics.Api.V2.Matches.Team.Item.Year.YearRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Common.Statbotics.Api.V2.Matches.Team.Item.WithTeamItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTeamItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/matches/team/{team}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Common.Statbotics.Api.V2.Matches.Team.Item.WithTeamItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTeamItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/matches/team/{team}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
