/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TheBlueAlliance.Api.Model;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Json.Serialization;

/// <summary>
/// GetStatus401Response
/// </summary>
public partial class GetStatus401Response : IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="GetStatus401Response" /> class.
    /// </summary>
    [JsonConstructor]
    protected GetStatus401Response() { }
    /// <summary>
    /// Initializes a new instance of the <see cref="GetStatus401Response" /> class.
    /// </summary>
    /// <param name="error">Authorization error description. (required).</param>
    public GetStatus401Response(string? error = default)
    {
        // to ensure "error" is required (not null)
        ArgumentNullException.ThrowIfNull(error);
        this.Error = error;
    }

    /// <summary>
    /// Authorization error description.
    /// </summary>
    /// <value>Authorization error description.</value>
    [JsonPropertyName("Error")]
    public string Error { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        StringBuilder sb = new();
        sb.AppendLine("class GetStatus401Response {");
        sb.Append("  Error: ").AppendLine(Error.ToString());
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return System.Text.Json.JsonSerializer.Serialize(this);
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}
