/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

namespace TheBlueAlliance.Api.Model;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Json.Serialization;

/// <summary>
/// A list of alliances, the teams on the alliances, and their score.
/// </summary>
public partial class MatchSimpleAlliances : IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MatchSimpleAlliances" /> class.
    /// </summary>
    [JsonConstructor]
    protected MatchSimpleAlliances() { }
    /// <summary>
    /// Initializes a new instance of the <see cref="MatchSimpleAlliances" /> class.
    /// </summary>
    /// <param name="red">red (required).</param>
    /// <param name="blue">blue (required).</param>
    public MatchSimpleAlliances(MatchAlliance? red = default, MatchAlliance? blue = default)
    {
        // to ensure "red" is required (not null)
        ArgumentNullException.ThrowIfNull(red);
        this.Red = red;
        // to ensure "blue" is required (not null)
        ArgumentNullException.ThrowIfNull(blue);
        this.Blue = blue;
    }

    /// <summary>
    /// Gets or Sets Red
    /// </summary>
    [JsonPropertyName("red")]
    public MatchAlliance Red { get; set; }

    /// <summary>
    /// Gets or Sets Blue
    /// </summary>
    [JsonPropertyName("blue")]
    public MatchAlliance Blue { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        StringBuilder sb = new();
        sb.AppendLine("class MatchSimpleAlliances {");
        sb.Append("  Red: ").AppendLine(Red.ToString());
        sb.Append("  Blue: ").AppendLine(Blue.ToString());
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return System.Text.Json.JsonSerializer.Serialize(this);
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}
