// <auto-generated/>
#pragma warning disable CS0618
using Common.Statbotics.Api.V2.Matches.Event.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Common.Statbotics.Api.V2.Matches.Event
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\matches\event
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Common.Statbotics.Api.v2.matches.event.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Common.Statbotics.Api.V2.Matches.Event.Item.WithEventItemRequestBuilder"/></returns>
        public global::Common.Statbotics.Api.V2.Matches.Event.Item.WithEventItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("event", position);
                return new global::Common.Statbotics.Api.V2.Matches.Event.Item.WithEventItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Common.Statbotics.Api.V2.Matches.Event.EventRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/matches/event", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Common.Statbotics.Api.V2.Matches.Event.EventRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/matches/event", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
