/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TheBlueAlliance.Model;
using TheBlueAlliance.Client;
using System.Reflection;

namespace TheBlueAlliance.Test.Model


    /// <summary>
    ///  Class for testing DistrictRankingEventPointsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DistrictRankingEventPointsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DistrictRankingEventPointsInner
        //private DistrictRankingEventPointsInner instance;

        public DistrictRankingEventPointsInnerTests()
        {
            // TODO uncomment below to create an instance of DistrictRankingEventPointsInner
            //instance = new DistrictRankingEventPointsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DistrictRankingEventPointsInner
        /// </summary>
        [Fact]
        public void DistrictRankingEventPointsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" DistrictRankingEventPointsInner
            //Assert.IsType<DistrictRankingEventPointsInner>(instance);
        }



        /// <summary>
        /// Test the property 'AlliancePoints'
        /// </summary>
        [Fact]
        public void AlliancePointsTest()
        {
            // TODO unit test for the property 'AlliancePoints'
        }


        /// <summary>
        /// Test the property 'AwardPoints'
        /// </summary>
        [Fact]
        public void AwardPointsTest()
        {
            // TODO unit test for the property 'AwardPoints'
        }


        /// <summary>
        /// Test the property 'DistrictCmp'
        /// </summary>
        [Fact]
        public void DistrictCmpTest()
        {
            // TODO unit test for the property 'DistrictCmp'
        }


        /// <summary>
        /// Test the property 'ElimPoints'
        /// </summary>
        [Fact]
        public void ElimPointsTest()
        {
            // TODO unit test for the property 'ElimPoints'
        }


        /// <summary>
        /// Test the property 'EventKey'
        /// </summary>
        [Fact]
        public void EventKeyTest()
        {
            // TODO unit test for the property 'EventKey'
        }


        /// <summary>
        /// Test the property 'QualPoints'
        /// </summary>
        [Fact]
        public void QualPointsTest()
        {
            // TODO unit test for the property 'QualPoints'
        }


        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
