/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TheBlueAlliance.Model;
using TheBlueAlliance.Client;
using System.Reflection;

namespace TheBlueAlliance.Test.Model


    /// <summary>
    ///  Class for testing DistrictInsightTeamData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DistrictInsightTeamDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DistrictInsightTeamData
        //private DistrictInsightTeamData instance;

        public DistrictInsightTeamDataTests()
        {
            // TODO uncomment below to create an instance of DistrictInsightTeamData
            //instance = new DistrictInsightTeamData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DistrictInsightTeamData
        /// </summary>
        [Fact]
        public void DistrictInsightTeamDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" DistrictInsightTeamData
            //Assert.IsType<DistrictInsightTeamData>(instance);
        }
    }
}
