/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TheBlueAlliance.Model;
using TheBlueAlliance.Client;
using System.Reflection;

namespace TheBlueAlliance.Test.Model


    /// <summary>
    ///  Class for testing GetTeamEventsStatusesByYear200ResponseValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetTeamEventsStatusesByYear200ResponseValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetTeamEventsStatusesByYear200ResponseValue
        //private GetTeamEventsStatusesByYear200ResponseValue instance;

        public GetTeamEventsStatusesByYear200ResponseValueTests()
        {
            // TODO uncomment below to create an instance of GetTeamEventsStatusesByYear200ResponseValue
            //instance = new GetTeamEventsStatusesByYear200ResponseValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetTeamEventsStatusesByYear200ResponseValue
        /// </summary>
        [Fact]
        public void GetTeamEventsStatusesByYear200ResponseValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetTeamEventsStatusesByYear200ResponseValue
            //Assert.IsType<GetTeamEventsStatusesByYear200ResponseValue>(instance);
        }



        /// <summary>
        /// Test the property 'Alliance'
        /// </summary>
        [Fact]
        public void AllianceTest()
        {
            // TODO unit test for the property 'Alliance'
        }


        /// <summary>
        /// Test the property 'AllianceStatusStr'
        /// </summary>
        [Fact]
        public void AllianceStatusStrTest()
        {
            // TODO unit test for the property 'AllianceStatusStr'
        }


        /// <summary>
        /// Test the property 'LastMatchKey'
        /// </summary>
        [Fact]
        public void LastMatchKeyTest()
        {
            // TODO unit test for the property 'LastMatchKey'
        }


        /// <summary>
        /// Test the property 'NextMatchKey'
        /// </summary>
        [Fact]
        public void NextMatchKeyTest()
        {
            // TODO unit test for the property 'NextMatchKey'
        }


        /// <summary>
        /// Test the property 'OverallStatusStr'
        /// </summary>
        [Fact]
        public void OverallStatusStrTest()
        {
            // TODO unit test for the property 'OverallStatusStr'
        }


        /// <summary>
        /// Test the property 'Playoff'
        /// </summary>
        [Fact]
        public void PlayoffTest()
        {
            // TODO unit test for the property 'Playoff'
        }


        /// <summary>
        /// Test the property 'PlayoffStatusStr'
        /// </summary>
        [Fact]
        public void PlayoffStatusStrTest()
        {
            // TODO unit test for the property 'PlayoffStatusStr'
        }


        /// <summary>
        /// Test the property 'Qual'
        /// </summary>
        [Fact]
        public void QualTest()
        {
            // TODO unit test for the property 'Qual'
        }
    }
}
