/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TheBlueAlliance.Model;
using TheBlueAlliance.Client;
using System.Reflection;

namespace TheBlueAlliance.Test.Model


    /// <summary>
    ///  Class for testing HubScore2026
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HubScore2026Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HubScore2026
        //private HubScore2026 instance;

        public HubScore2026Tests()
        {
            // TODO uncomment below to create an instance of HubScore2026
            //instance = new HubScore2026();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HubScore2026
        /// </summary>
        [Fact]
        public void HubScore2026InstanceTest()
        {
            // TODO uncomment below to test "IsType" HubScore2026
            //Assert.IsType<HubScore2026>(instance);
        }



        /// <summary>
        /// Test the property 'AutoCount'
        /// </summary>
        [Fact]
        public void AutoCountTest()
        {
            // TODO unit test for the property 'AutoCount'
        }


        /// <summary>
        /// Test the property 'AutoPoints'
        /// </summary>
        [Fact]
        public void AutoPointsTest()
        {
            // TODO unit test for the property 'AutoPoints'
        }


        /// <summary>
        /// Test the property 'EndgameCount'
        /// </summary>
        [Fact]
        public void EndgameCountTest()
        {
            // TODO unit test for the property 'EndgameCount'
        }


        /// <summary>
        /// Test the property 'EndgamePoints'
        /// </summary>
        [Fact]
        public void EndgamePointsTest()
        {
            // TODO unit test for the property 'EndgamePoints'
        }


        /// <summary>
        /// Test the property 'Shift1Count'
        /// </summary>
        [Fact]
        public void Shift1CountTest()
        {
            // TODO unit test for the property 'Shift1Count'
        }


        /// <summary>
        /// Test the property 'Shift1Points'
        /// </summary>
        [Fact]
        public void Shift1PointsTest()
        {
            // TODO unit test for the property 'Shift1Points'
        }


        /// <summary>
        /// Test the property 'Shift2Count'
        /// </summary>
        [Fact]
        public void Shift2CountTest()
        {
            // TODO unit test for the property 'Shift2Count'
        }


        /// <summary>
        /// Test the property 'Shift2Points'
        /// </summary>
        [Fact]
        public void Shift2PointsTest()
        {
            // TODO unit test for the property 'Shift2Points'
        }


        /// <summary>
        /// Test the property 'Shift3Count'
        /// </summary>
        [Fact]
        public void Shift3CountTest()
        {
            // TODO unit test for the property 'Shift3Count'
        }


        /// <summary>
        /// Test the property 'Shift3Points'
        /// </summary>
        [Fact]
        public void Shift3PointsTest()
        {
            // TODO unit test for the property 'Shift3Points'
        }


        /// <summary>
        /// Test the property 'Shift4Count'
        /// </summary>
        [Fact]
        public void Shift4CountTest()
        {
            // TODO unit test for the property 'Shift4Count'
        }


        /// <summary>
        /// Test the property 'Shift4Points'
        /// </summary>
        [Fact]
        public void Shift4PointsTest()
        {
            // TODO unit test for the property 'Shift4Points'
        }


        /// <summary>
        /// Test the property 'TeleopCount'
        /// </summary>
        [Fact]
        public void TeleopCountTest()
        {
            // TODO unit test for the property 'TeleopCount'
        }


        /// <summary>
        /// Test the property 'TeleopPoints'
        /// </summary>
        [Fact]
        public void TeleopPointsTest()
        {
            // TODO unit test for the property 'TeleopPoints'
        }


        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }


        /// <summary>
        /// Test the property 'TotalPoints'
        /// </summary>
        [Fact]
        public void TotalPointsTest()
        {
            // TODO unit test for the property 'TotalPoints'
        }


        /// <summary>
        /// Test the property 'TransitionCount'
        /// </summary>
        [Fact]
        public void TransitionCountTest()
        {
            // TODO unit test for the property 'TransitionCount'
        }


        /// <summary>
        /// Test the property 'TransitionPoints'
        /// </summary>
        [Fact]
        public void TransitionPointsTest()
        {
            // TODO unit test for the property 'TransitionPoints'
        }
    }
}
