/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).
 *
 * The version of the OpenAPI document: 3.9.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TheBlueAlliance.Model;
using TheBlueAlliance.Client;
using System.Reflection;

namespace TheBlueAlliance.Test.Model


    /// <summary>
    ///  Class for testing MatchScoreBreakdown2023AllianceAutoCommunity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchScoreBreakdown2023AllianceAutoCommunityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatchScoreBreakdown2023AllianceAutoCommunity
        //private MatchScoreBreakdown2023AllianceAutoCommunity instance;

        public MatchScoreBreakdown2023AllianceAutoCommunityTests()
        {
            // TODO uncomment below to create an instance of MatchScoreBreakdown2023AllianceAutoCommunity
            //instance = new MatchScoreBreakdown2023AllianceAutoCommunity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatchScoreBreakdown2023AllianceAutoCommunity
        /// </summary>
        [Fact]
        public void MatchScoreBreakdown2023AllianceAutoCommunityInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatchScoreBreakdown2023AllianceAutoCommunity
            //Assert.IsType<MatchScoreBreakdown2023AllianceAutoCommunity>(instance);
        }



        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Fact]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }


        /// <summary>
        /// Test the property 'M'
        /// </summary>
        [Fact]
        public void MTest()
        {
            // TODO unit test for the property 'M'
        }


        /// <summary>
        /// Test the property 'T'
        /// </summary>
        [Fact]
        public void TTest()
        {
            // TODO unit test for the property 'T'
        }
    }
}
