@webhook_url = {{DiscordBotFunctionApp_HostAddress}}/api/tba/webhook{{auth_code}}

### Send ping request
POST {{webhook_url}}
content-type: application/json

{
  "message_data": {
    "title": "Test Message",
    "desc": "This is a test message ensuring your device can receive push messages from The Blue Alliance."
  },
  "message_type": "ping"
}

### Send verification request
POST {{webhook_url}}
content-type: application/json

{
  "message_type": "verification",
  "message_data": {
    "verification_key": "foo"
  }
}

### Send match_score notification
POST {{DiscordBotFunctionApp_HostAddress}}/api/tba/webhook
content-type: application/json

{
    "message_type": "match_score",
    "message_data": {
        "event_key": "2024wabon",
        "match_key": "2024wabon_qm4",
        "event_name": "PNW District Bonney Lake Event",
        "match": {
            "key": "2024wabon_qm4",
            "event_key": "2024wabon",
            "comp_level": "qm",
            "set_number": 1,
            "match_number": 4,
            "alliances": {
                "red": {
                    "team_keys": [
                        "frc3218",
                        "frc2980",
                        "frc2046"
                    ],
                    "score": 57,
                    "surrogate_team_keys": [],
                    "dq_team_keys": []
                },
                "blue": {
                    "team_keys": [
                        "frc5683",
                        "frc3049",
                        "frc3663"
                    ],
                    "score": 55,
                    "surrogate_team_keys": [],
                    "dq_team_keys": []
                }
            },
            "winning_alliance": "red",
            "score_breakdown": {
                "red": {
                    "coopertitionBonusAchieved": false,
                    "melodyBonusThresholdCoop": 15,
                    "melodyBonusThresholdNonCoop": 18,
                    "melodyBonusThreshold": 18,
                    "ensembleBonusStagePointsThreshold": 10,
                    "ensembleBonusOnStageRobotsThreshold": 2,
                    "autoLineRobot1": "No",
                    "endGameRobot1": "Parked",
                    "autoLineRobot2": "Yes",
                    "endGameRobot2": "CenterStage",
                    "autoLineRobot3": "Yes",
                    "endGameRobot3": "StageRight",
                    "autoAmpNoteCount": 0,
                    "autoSpeakerNoteCount": 3,
                    "teleopAmpNoteCount": 1,
                    "teleopSpeakerNoteCount": 15,
                    "teleopSpeakerNoteAmplifiedCount": 0,
                    "micCenterStage": false,
                    "micStageLeft": false,
                    "micStageRight": false,
                    "trapCenterStage": false,
                    "trapStageLeft": false,
                    "trapStageRight": false,
                    "autoPoints": 19,
                    "autoAmpNotePoints": 0,
                    "autoSpeakerNotePoints": 15,
                    "autoTotalNotePoints": 15,
                    "autoLeavePoints": 4,
                    "teleopPoints": 38,
                    "teleopAmpNotePoints": 1,
                    "teleopSpeakerNotePoints": 30,
                    "teleopSpeakerNoteAmplifiedPoints": 0,
                    "teleopTotalNotePoints": 31,
                    "endGameParkPoints": 1,
                    "endGameOnStagePoints": 6,
                    "endGameSpotLightBonusPoints": 0,
                    "endGameHarmonyPoints": 0,
                    "endGameNoteInTrapPoints": 0,
                    "endGameTotalStagePoints": 7,
                    "melodyBonusAchieved": true,
                    "ensembleBonusAchieved": false,
                    "coopertitionCriteriaMet": false,
                    "coopNotePlayed": false,
                    "foulCount": 0,
                    "techFoulCount": 0,
                    "g206Penalty": false,
                    "g408Penalty": false,
                    "g424Penalty": false,
                    "adjustPoints": 0,
                    "foulPoints": 0,
                    "rp": 3,
                    "totalPoints": 57
                },
                "blue": {
                    "coopertitionBonusAchieved": false,
                    "melodyBonusThresholdCoop": 15,
                    "melodyBonusThresholdNonCoop": 18,
                    "melodyBonusThreshold": 18,
                    "ensembleBonusStagePointsThreshold": 10,
                    "ensembleBonusOnStageRobotsThreshold": 2,
                    "autoLineRobot1": "No",
                    "endGameRobot1": "CenterStage",
                    "autoLineRobot2": "No",
                    "endGameRobot2": "Parked",
                    "autoLineRobot3": "Yes",
                    "endGameRobot3": "Parked",
                    "autoAmpNoteCount": 0,
                    "autoSpeakerNoteCount": 4,
                    "teleopAmpNoteCount": 0,
                    "teleopSpeakerNoteCount": 14,
                    "teleopSpeakerNoteAmplifiedCount": 0,
                    "micCenterStage": false,
                    "micStageLeft": false,
                    "micStageRight": false,
                    "trapCenterStage": false,
                    "trapStageLeft": false,
                    "trapStageRight": false,
                    "autoPoints": 22,
                    "autoAmpNotePoints": 0,
                    "autoSpeakerNotePoints": 20,
                    "autoTotalNotePoints": 20,
                    "autoLeavePoints": 2,
                    "teleopPoints": 33,
                    "teleopAmpNotePoints": 0,
                    "teleopSpeakerNotePoints": 28,
                    "teleopSpeakerNoteAmplifiedPoints": 0,
                    "teleopTotalNotePoints": 28,
                    "endGameParkPoints": 2,
                    "endGameOnStagePoints": 3,
                    "endGameSpotLightBonusPoints": 0,
                    "endGameHarmonyPoints": 0,
                    "endGameNoteInTrapPoints": 0,
                    "endGameTotalStagePoints": 5,
                    "melodyBonusAchieved": true,
                    "ensembleBonusAchieved": false,
                    "coopertitionCriteriaMet": false,
                    "coopNotePlayed": false,
                    "foulCount": 0,
                    "techFoulCount": 0,
                    "g206Penalty": false,
                    "g408Penalty": false,
                    "g424Penalty": false,
                    "adjustPoints": 0,
                    "foulPoints": 0,
                    "rp": 1,
                    "totalPoints": 55
                }
            },
            "videos": [
                {
                    "type": "youtube",
                    "key": "w2-XMPqrWdo"
                }
            ],
            "time": 1710614460,
            "actual_time": 1710614660,
            "predicted_time": 1710622701,
            "post_result_time": 1710614938
        }
    }
}

### Send upcoming_match notification
POST {{webhook_url}}
content-type: application/json

{
  "message_data": {
    "event_key": "2024orsal",
    "match_key": "2024orsal_qm5",
    "event_name": "New England FRC Region Championship",
    "team_keys": [
      "frc195",
      "frc558",
      "frc5122",
      "frc2046",
      "frc230",
      "frc4055"
    ],
    "scheduled_time": 1397330280,
    "predicted_time": 1397330280,
    "webcast": {
      "type": "twitch",
      "channel": "nefirst_blue"
    }
  },
  "message_type": "upcoming_match"
}

### Send alliance_selection notification
POST {{webhook_url}}
content-type: application/json

{
  "message_data": {
    "event_name": "New England FRC Region Championship",
    "event_key": "2024orsal",
    "event": {
      "key": "2024orsal",
      "website": "http://www.nefirst.org/",
      "official": true,
      "end_date": "2014-04-12",
      "name": "New England FRC Region Championship",
      "short_name": "New England",
      "facebook_eid": null,
      "event_district_string": "New England",
      "venue_address": "Boston University\nAgganis Arena\nBoston, MA 02215\nUSA",
      "event_district": 3,
      "location": "Boston, MA, USA",
      "event_code": "orsal",
      "year": 2014,
      "webcast": [],
      "alliances": [
        {
          "declines": [],
          "picks": [
            "frc195",
            "frc2046",
            "frc5122"
          ]
        },
        {
          "declines": ["frc2910"],
          "picks": [
            "frc1153",
            "frc125",
            "frc4048"
          ]
        },
        {
          "declines": [],
          "picks": [
            "frc230",
            "frc177",
            "frc4055"
          ]
        },
        {
          "declines": [],
          "picks": [
            "frc716",
            "frc78",
            "frc811"
          ]
        },
        {
          "declines": [],
          "picks": [
            "frc1519",
            "frc3467",
            "frc58"
          ]
        },
        {
          "declines": [],
          "picks": [
            "frc131",
            "frc175",
            "frc1073"
          ]
        },
        {
          "declines": [],
          "picks": [
            "frc228",
            "frc3525",
            "frc2168"
          ]
        },
        {
          "declines": [],
          "picks": [
            "frc172",
            "frc1058",
            "frc2067"
          ]
        }
      ],
      "event_type_string": "District Championship",
      "start_date": "2014-04-10",
      "event_type": 2
    }
  },
  "message_type": "alliance_selection"
}

### Send awards_posted notification
POST {{webhook_url}}
content-type: application/json

{
  "message_data": {
    "event_key": "2024orsal",
    "event_name": "New England FRC Region Championship",
    "awards": [
      {
        "event_key": "2024orsal",
        "award_type": 20,
        "name": "Regional Chairman's Award",
        "recipient_list": [
          {
            "team_number": 2046,
            "awardee": null
          }
        ],
        "year": 2014
      }
    ]
  },
  "message_type": "awards_posted"
}
