@base_url = http://localhost:7240/api

### Send ping request
POST {{base_url}}/tba/webhook
content-type: application/json

{
  "message_type": "ping",
  "message_data": "ping data"
}

### Send verification request
POST {{base_url}}/tba/webhook
content-type: application/json

{
  "message_type": "verification",
  "message_data": {
    "verification_key": "foo"
  }
}

### Send subscription request
POST {{base_url}}/subscribe
content-type: application/json

{
  "team":5122,
  "event":"2014necmp",
  "guildId": "996567213614055504",
  "channelId": "1328806657303642205"
}

### Send match_score notification
POST {{base_url}}/tba/webhook
content-type: application/json

{
  "message_data": {
    "event_name": "Test event",
    "match": {
      "comp_level": "f",
      "match_number": 1,
      "videos": [],
      "time_string": "3:18 PM",
      "set_number": 1,
      "key": "2024orsal_qm5",
      "time": 1397330280,
      "score_breakdown": null,
      "alliances": {
        "blue": {
          "score": 154,
          "team_keys": [
            "frc177",
            "frc230",
            "frc2046"
          ]
        },
        "red": {
          "score": 78,
          "team_keys": [
            "frc195",
            "frc558",
            "frc5122"
          ]
        }
      },
      "event_key": "2024orsal"
    }
  },
  "message_type": "match_score"
}