name: Build & Run UTs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-debug:
    name: Build & Test Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Debug
        run: dotnet build --configuration Debug
         
      - name: Run UTs
        run: dotnet test --configuration Debug --no-build


  build-release:
    name: Build & Test Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Release
        run: dotnet build --configuration Release
         
      - name: Run UTs
        run: dotnet test --configuration Release --no-build
