// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Common.Tba.Api.Models
{
    /// <summary>The competition level the match was played at.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Match_comp_level
    {
        [EnumMember(Value = "qm")]
        #pragma warning disable CS1591
        Qm,
        #pragma warning restore CS1591
        [EnumMember(Value = "ef")]
        #pragma warning disable CS1591
        Ef,
        #pragma warning restore CS1591
        [EnumMember(Value = "qf")]
        #pragma warning disable CS1591
        Qf,
        #pragma warning restore CS1591
        [EnumMember(Value = "sf")]
        #pragma warning disable CS1591
        Sf,
        #pragma warning restore CS1591
        [EnumMember(Value = "f")]
        #pragma warning disable CS1591
        F,
        #pragma warning restore CS1591
    }
}
